name: Release Linux

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch: {}

env:
  NODE_VERSION: 22
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  build-linux:
    name: Build Linux packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libarchive-tools libopenjp2-tools squashfs-tools

      - name: Install Zig
        uses: mlugg/setup-zig@v2

      - name: Install FPM
        run: sudo gem install fpm

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Force git deps to HTTPS
        run: |
          git config --global url.https://github.com/.insteadof ssh://git@github.com/
          git config --global url.https://github.com/.insteadof git@github.com:

      - name: npm ci
        run: npm ci --no-audit --no-fund

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (.deb + AppImage)
        run: task package -- --linux deb AppImage
        env:
          USE_SYSTEM_FPM: "true"

      - name: Upload build artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v5
        with:
          name: linux-packages
          path: |
            make/*.deb
            make/*.AppImage

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            make/*.deb
            make/*.AppImage

